import {useMemo} from 'react'
import Head from 'next/head'
import { Fraunces } from '@next/font/google'
import { Box, Button, HStack, Heading, Text } from '@chakra-ui/react'
import { Navbar, ContainerComp, ScrollIcon, Carousel, CustomerItem, PlanItem } from '@/components'
import Image from 'next/image'
import bannerImage from '../../public/banner.png'
import aboutImage from '../../public/about.png'

const fraunces = Fraunces({ subsets: ['latin'], weight: '600' })

export default function Home() {

  
  const planItems = useMemo(() => {
    const plans = [
      {
        name: 'Starter Pack',
        price: 345321,
        features: [
          '9 Feeds',
          '2 Story',
          'Automatic Post'
        ],
        isPriority: false
      },
      {
        name: 'Medium Pack',
        price: 645321,
        features: [
          '15 Feeds',
          '5 Story',
          'Automatic Post'
        ],
        isPriority: true
      },
      {
        name: 'Professional Pack',
        price: 1080000,
        features: [
          '25 Feeds',
          '9 Story',
          'Automatic Post',
          'Statistic Instagram Report'
        ],
        isPriority: false
      },
    ]

    return plans.map(({name, price, features, isPriority}) => <PlanItem name={name} price={price} features={features} isPriority={isPriority} />);
  }, []);

  const clientItems = useMemo(() => {
    const customers = [
      {
        name: 'Vicko Effendy',
        testimoni: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ad alias, assumenda aperiam iusto, neque dolore itaque qui mollitia officiis'
      },
      {
        name: 'Alfan Budi',
        testimoni: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ad alias, assumenda aperiam iusto, neque dolore itaque qui mollitia officiis'
      },
      {
        name: 'Zein Abdillah',
        testimoni: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ad alias, assumenda aperiam iusto, neque dolore itaque qui mollitia officiis'
      },
      {
        name: 'Sangaji Sumanto',
        testimoni: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ad alias, assumenda aperiam iusto, neque dolore itaque qui mollitia officiis'
      },
    ]

    return customers.map(({name, testimoni}) => <CustomerItem avatar={`https://bit.ly/${name.replace(' ', '-')}`} name={name} testimoni={testimoni}/>);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        {/** Banner Start */}
        <Box py="20">
          <ContainerComp>
            <HStack>
              <Box minW="50%" >
                <HStack alignItems="end">
                  <Heading as='h1' fontSize="5xl" className={fraunces.className} mb="6">
                    Axcelento
                  </Heading>
                </HStack>
                  <Heading as='h1' fontSize="2xl" className={fraunces.className}>
                    We Are Here
                  </Heading>
                <Heading as='h1' fontSize="3xl" className={fraunces.className}>
                  To Help Your Bussiness!
                </Heading>
              </Box>
              <Box >
                <Image src={bannerImage} alt="illustration banner" />
              </Box>
            </HStack>
            <ScrollIcon/>
          </ContainerComp>
        </Box>
        {/** Banner End */}

        {/** About Start */}
        <Box py="20" pb="0">
          <ContainerComp>
            <HStack>
              <Box p="8" maxW="xl" borderRadius="xl" order="2">
                <Heading as='h2' fontSize="3xl" fontWeight="semibold" mb="5" textAlign="center" className={fraunces.className}>
                  About Us
                </Heading>
                <Text>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit ad alias, assumenda aperiam iusto, neque dolore itaque qui mollitia officiis fugiat, quibusdam non natus! Asperiores vero harum iste eum non?
                </Text>
              </Box>
              <Box order="1">
                <Image src={aboutImage} alt="illustration banner" />
              </Box> 
            </HStack>
          </ContainerComp>
        </Box>
        {/** About End */}
        
        {/** Portfolio Start */}
        <Box py="20" backgroundColor="dark">
          <ContainerComp>
              <Heading as='h2' fontSize="3xl" fontWeight="semibold" mb="5" color="white" textAlign="center" className={fraunces.className}>
                Projects We've Worked On
              </Heading>
          </ContainerComp>
        </Box>
        {/** Portfolio End */}

        {/** Packages Start */}
        <Box py="20">
          <ContainerComp>
              <Heading as='h2' fontSize="6xl" fontWeight="semibold"className={fraunces.className}>
                We've Got a Plan
              </Heading>
              <Heading as='h2' fontSize="2xl" color="gray.400" fontWeight="light" mb="12" className={fraunces.className}>
                That's Perfect For You
              </Heading>
              <HStack gap="5">
                {planItems}
              </HStack>
          </ContainerComp>
        </Box>
        {/** Packages End */}

        {/** Clients Start */}
        <Box py="20">
          <ContainerComp>
              <Heading as='h2' fontSize="3xl" fontWeight="semibold"textAlign="center" className={fraunces.className}>
                Our Customers
              </Heading>
              <Heading as='h2' fontSize="lg" color="gray.400" fontWeight="light" mb="5" textAlign="center" className={fraunces.className}>
                Testimonial
              </Heading>
              <Carousel items={clientItems} />
          </ContainerComp>
        </Box>
        {/** Clients End */}
      </main>
    </>
  )
}
